# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-15 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_posttagrelation_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
